name: Code Analysis

on:
    pull_request: null
    push: null

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'ECS'
                        run: 'composer fix-cs --ansi'

                    -
                        name: 'PHPStan'
                        run: 'composer phpstan --ansi'

                    -
                        name: 'Unit Tests'
                        run: 'vendor/bin/phpunit'

                    -
                        name: 'Check Active Classes'
                        run: 'vendor/bin/easy-ci check-active-class src --ansi'

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}